spring:
  application:
    name: yarch-examples-ddd
  datasource:
    url: jdbc:postgresql://localhost:5432/yarch-examples-ddd
    username: yarch-examples-ddd
    password: yarch-examples-ddd
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

mybatis-plus:
  global-config:
    banner: false

yarch:
  env: local
  auth:
    secret: examples-demo-secret-please-rotate
